//
// Created by CryosArtic on 6/27/2026.
//

#ifndef DRIVESYSTEM_MICROCONTROLLER_H
#define DRIVESYSTEM_MICROCONTROLLER_H


enum Microcontroller {
    ARDUINO_UNO_R3,
    ARDUINO_UNO_Q,
    ESP32_WROOM_32UE,
    ESP32_WROVER_E,
    RASPBERRY_PI_PICO_W,
    RASPBERRY_PI_PICO_2_W
};


#endif //DRIVESYSTEM_MICROCONTROLLER_H
